### PR TITLE
fix: windows paths break code generator

### LINKED ISSUE #2: Error: broken import paths when running on Windows
When running on Windows, bun uses paths with backslashes ("\\"), which the code generator treats as escape characters.\
This leads to the paths being broken in the generated tests' code:

```
# Unhandled error between tests
-------------------------------
error: Cannot find package '@aboviun-test-cucumbersrcindex.ts' from 'features\example.feature'
```

### PR DESCRIPTION
**Pull request by Raiondesu**
Code generator treats "\\" in windows paths as an escape character, leading to imports not being resolved properly when run on windows.

This PR makes sure all occurrences of `\` in relevant paths are replaced with `/` to avoid this issue.

Fixes #2

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+/**
+ * Replaces windows-style "\\" with normal "/" for correct module resolution,
+ * because the code generator treats "\\" as an escape character (because it is)
+ *
+ * @param path a path to normalize
+ * @returns a normalized path
+ */
+export const normalizePath = (path: string): string => path.replaceAll('\\', '/');
```
Comment (joakimbeng) [inline src/utils.ts]:
```suggestion
export const normalizePath = (path: string): string => path.replaceAll('\\', '/');

```

**Review by joakimbeng — COMMENTED** [review]
Good catch! Thank you 😃

**Review by joakimbeng — APPROVED** [review]
